### ISSUE TITLE
Setup button doesn't do anything

### ISSUE THREAD

**Issue by axtens** [prrvchr/smtpMailerOOo#7]
Installed for everyone. Spooler is started then stops itself. Pressing "Setup" doesn't work.
```
  event no thread   date       time        (class/method:) message
         1      932 2024-06-12 09:38:21.139028100 OptionsManager::__init__(): OptionManger has been correctly initialized.
         2      932 2024-06-12 09:38:23.619848500 OptionsHandler::callHandlerMethod(): An unexpected exception: <class 'TypeError'>: not all arguments converted during string formatting, traceback follows
  File "C:\Users\bugma\scoop\apps\libreoffice\current\LibreOffice\share\uno_packages\cache\uno_packages\lu33224958ro.tmp_\eMailerOOo.oxt\service\pythonpath\emailer\maildispatch.py", line 105, in dispatch
    self._showMsgBox(*oauth2)
  File "C:\Users\bugma\scoop\apps\libreoffice\current\LibreOffice\share\uno_packages\cache\uno_packages\lu33224958ro.tmp_\eMailerOOo.oxt\service\pythonpath\emailer\maildispatch.py", line 257, in _showMsgBox
    message = resource.resolveString(code) % args

 at C:/cygwin64/home/buildslave/source/libo-core/pyuno/source/module/pyuno_runtime.cxx:950 has occurred, producing a series of exceptions: Traceback (most recent call last):
  File "C:\Users\bugma\scoop\apps\libreoffice\current\LibreOffice\share\uno_packages\cache\uno_packages\lu33224958ro.tmp_\eMailerOOo.oxt\service\OptionsHandler.py", line 75, in callHandlerMethod
    self._manager.showIspdb()
  File "C:\Users\bugma\scoop\apps\libreoffice\current\LibreOffice\share\uno_packages\cache\uno_packages\lu33224958ro.tmp_\eMailerOOo.oxt\service\pythonpath\emailer\options\optionsmanager.py", line 101, in showIspdb
    executeFrameDispatch(self._ctx, frame, 'smtp:ispdb')
  File "C:\Users\bugma\scoop\apps\libreoffice\current\LibreOffice\share\uno_packages\cache\uno_packages\lu33224958ro.tmp_\eMailerOOo.oxt\service\pythonpath\emailer\unotool\unotool.py", line 328, in executeFrameDispatch
    dispatcher.dispatch(url, arguments)
uno.com.sun.star.uno.RuntimeException: <class 'TypeError'>: not all arguments converted during string formatting, traceback follows
  File "C:\Users\bugma\scoop\apps\libreoffice\current\LibreOffice\share\uno_packages\cache\uno_packages\lu33224958ro.tmp_\eMailerOOo.oxt\service\pythonpath\emailer\maildispatch.py", line 105, in dispatch
    self._showMsgBox(*oauth2)
  File "C:\Users\bugma\scoop\apps\libreoffice\current\LibreOffice\share\uno_packages\cache\uno_packages\lu33224958ro.tmp_\eMailerOOo.oxt\service\pythonpath\emailer\maildispatch.py", line 257, in _showMsgBox
    message = resource.resolveString(code) % args

 at C:/cygwin64/home/buildslave/source/libo-core/pyuno/source/module/pyuno_runtime.cxx:950
```

**Comment by prrvchr** [comment]
Hi axtens,

You are right there was a problem that I have just corrected in the new version 1.2.3.

I remind you that you must install the [OAuth2OOo](https://prrvchr.github.io/OAuth2OOo/) and [jdbcDriverOOo](https://prrvchr.github.io/jdbcDriverOOo/) extension to be able to use **eMailerOOo**.

The problem having been resolved, I am closing but you are free to reopen if necessary.
